name: gitleaks

on:
    pull_request:
    push:
        branches: [ main, develop ]

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Run gitleaks
              uses: zricethezav/gitleaks-action@master
